### ISSUE TITLE
ValueError: level must be >= 0

### ISSUE THREAD

**Issue by Snoopy2017** [fwenzel/collage#1]
When i try to run the script with python3.6 it says: 

```
Traceback (most recent call last):
  File "/Users/thatsme/Downloads/collage/collage.py", line 36, in <module>
    [], -1)
ValueError: level must be >= 0
```

sorry if im foolish. im totally new to programming.

**Comment by fwenzel** [comment]
It's probably not compatible with Python 3 yet, but it can also probably be made Python 3 compatible somewhat easily.

**Comment by fwenzel** [comment]
You can probably remove most of the settings stuff in the code and just hardcode what you need.

https://github.com/fwenzel/collage/blob/master/collage.py#L34-L41

**Comment by fwenzel** [comment]
This should be fixed now, thanks @bj00rn !
